### ISSUE TITLE
Update `NPM_TOKEN` secret

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/osv-offline#53]
The current `NPM_TOKEN` secret allows publishing in the `@jamiemagee` npm package scope. After moving the packages to the `@renovatebot` scope, the secret needs to be updated.

**Comment by rarkins** [comment]
Needs the `renovate-bot` user on npm, from the looks of it (looked at https://www.npmjs.com/package/@renovatebot/pep440).

I guess we update the token first, and then attempt a publish?

**Comment by rarkins** [comment]
I've added an automation token for the `renovate-bot` user on npm
